from pathlib import Path

import pytest
import streamlit as st
from streamlit.testing.v1 import AppTest

APP = Path(__file__).resolve().parents[2] / "app/ui/streamlit_app.py"
MIME = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"


@pytest.fixture
def ui(tmp_path, monkeypatch):
    monkeypatch.setenv("DATA_DIR", str(tmp_path / "ui_data"))
    st.cache_resource.clear()
    app = AppTest.from_file(str(APP), default_timeout=30).run()
    yield app
    st.cache_resource.clear()


def process_button(ui):
    return next(button for button in ui.button if button.label == "Process workbook")


def test_ui_upload_and_results(ui, samples):
    assert not ui.exception
    assert process_button(ui).disabled
    ui.file_uploader[0].set_value(
        ("cross_sheet.xlsx", samples["fixture_cross_sheet"].read_bytes(), MIME)
    ).run()
    assert not process_button(ui).disabled
    process_button(ui).click().run()
    assert not ui.exception
    assert not ui.error
    assert {metric.label: metric.value for metric in ui.metric} == {
        "Sheets": "3",
        "Tables": "1",
        "Formulas": "2",
        "Dependencies": "3",
        "Images": "0",
        "Charts": "0",
        "Quality score": "93%",
        "Review required": "2",
    }
    assert "result_run_id" in ui.session_state
    formula_sheet = next(widget for widget in ui.selectbox if widget.label == "Formula sheet")
    formula_sheet.select("Summary").run()
    assert not ui.exception
    agent = next(checkbox for checkbox in ui.checkbox if checkbox.label.startswith("Ask the local"))
    assert agent.disabled
    assert any(button.label == "Render preview" for button in ui.button)
    # Reruns for inspection must not register another upload/run.
    run_id = ui.session_state["result_run_id"]
    ui.run()
    assert ui.session_state["result_run_id"] == run_id


def test_ui_invalid_upload(ui):
    ui.file_uploader[0].set_value(("invalid.xlsx", b"not a workbook", MIME)).run()
    process_button(ui).click().run()
    assert ui.error
    assert not ui.exception
    assert "result_run_id" not in ui.session_state


def test_ui_sample(ui, samples):
    # Samples are generated by the standard repository setup command.
    from app.ui.streamlit_app import SAMPLES_DIR

    if not list(SAMPLES_DIR.glob("fixture_*.xlsx")):
        pytest.skip("Repository samples have not been generated")
    ui.radio[0].set_value("Try a sample").run()
    process_button(ui).click().run()
    assert not ui.exception
    assert not ui.error
    assert len(ui.metric) == 8


def test_shared_writer_lock(settings, samples):
    import fcntl

    from app.services.run_service import BusyError, RunService

    service = RunService(settings)
    with samples["fixture_simple"].open("rb") as source:
        workbook = service.upload(source, "simple.xlsx")
    with settings.duckdb_path.with_suffix(".lock").open("a") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
        with pytest.raises(BusyError):
            service.process(workbook.workbook_id)
    assert service.process(workbook.workbook_id).stage == "COMPLETED_WITH_WARNINGS"
